import type { CanonicalRequest, CanonicalResponse, ProviderAccount, Usage } from "../shared/types";
import { AdminError, GatewayError } from "../shared/errors";
import type { ProvidersRepo } from "../store/repos/providers";
import { XAI_BASE_URL, refreshAccessToken, extractEmailFromAccessToken } from "../admin/xai-oauth";
import { SseParser } from "./translator/stream";
import { isPermanentRefreshFailure, markReauthRequired, withRefreshLock } from "./refresh";
import { normalizeUsage } from "./promptCache";
import { ulid } from "../utils/id";

const SESSION_TTL_MS = 30 * 60_000;
const MAX_TRACKED_SESSIONS = 2_000;
const RETRIABLE_XAI_STATUSES = new Set([429, 502, 503]);
const sessionTurns = new Map<string, { turn: number; lastUsed: number }>();

export interface XaiRequestContext {
  sessionId?: string;
  requestId?: string;
}

const REFRESH_THRESHOLD_MS = 5 * 60_000;

/** The Grok CLI OAuth API implements the Responses dialect. */
export function xaiResponsesUrl(): string {
  return `${XAI_BASE_URL}/responses`;
}

/** The Grok CLI also exposes a standard OpenAI-compatible Chat Completions endpoint. */
export function xaiChatCompletionsUrl(): string {
  return `${XAI_BASE_URL}/chat/completions`;
}

const SERVER_ID_PATTERN = /^(rs|fc|resp|msg)_/;
const NATIVE_GROK_CLI_ITEM_ID = /^(?:rs|msg|fc)_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Fields accepted by cli-chat-proxy Responses API (mirrors Codex allowlist + Grok extras). */
const RESPONSES_API_ALLOWLIST = new Set([
  "model", "input", "instructions", "tools", "tool_choice",
  "stream", "store", "reasoning", "include", "temperature",
  "top_p", "max_output_tokens", "parallel_tool_calls", "text", "metadata",
  "prompt_cache_key",
]);

/** Hosted tool types executed server-side by Grok CLI backend — keep as-is. */
const HOSTED_TOOL_TYPES = new Set(["web_search", "x_search", "web_search_preview", "file_search"]);

/** Reasoning effort levels recognized by Grok CLI. */
const EFFORT_LEVELS = ["low", "medium", "high", "xhigh"];
const VERIFIED_TOOL_WORKFLOW = [
  "For tool-based work, follow a careful, verified engineering workflow.",
  "First inspect the relevant files, constraints, and current state; do not guess or overwrite blindly.",
  "Form a short plan, use only necessary tools, and make the smallest safe change that satisfies the request.",
  "Preserve existing behavior unless the request explicitly changes it.",
  "After every change, run an appropriate verification and inspect its result before reporting completion.",
  "If verification fails or is not possible, state the blocker clearly and do not claim success.",
  "Reply in the user's language; use Bahasa Indonesia when the user writes in Indonesian.",
].join(" ");

/** Only grok-4.5 supports reasoning.effort; grok-build rejects it. */
export function supportsReasoningEffort(model: string): boolean {
  return /^grok-4\.5(?:$|-)/.test(model);
}

function normalizeEffort(value: string | undefined): string {
  if (!value) return "high";
  const effort = value.trim().toLowerCase();
  if (effort === "max") return "xhigh";
  if (EFFORT_LEVELS.includes(effort)) return effort;
  return "high";
}

function textOf(content: CanonicalRequest["messages"][number]["content"]): string {
  if (typeof content === "string") return content;
  return content
    .map((part) => {
      if (typeof part === "string") return part;
      if (part.type === "text") return part.text;
      return "";
    })
    .filter(Boolean)
    .join("\n");
}

/** Check whether an id looks like it was generated by a Grok server response. */
function isServerGeneratedId(id: unknown): boolean {
  return typeof id === "string" && SERVER_ID_PATTERN.test(id);
}

/**
 * Normalizes the Chat Completions tool-choice shape to Grok CLI's Responses
 * shape. Grok CLI accepts flat function tools, not the nested Chat shape.
 */
function xaiToolChoice(choice: unknown, toolNames: Set<string>): unknown {
  if (choice === "auto" || choice === "none" || choice === "required") return choice;
  if (!choice || typeof choice !== "object" || Array.isArray(choice)) return undefined;

  const value = choice as Record<string, unknown>;
  const nested = value.function;
  const nestedName = nested && typeof nested === "object" && !Array.isArray(nested)
    ? (nested as Record<string, unknown>).name
    : undefined;
  const name = typeof value.name === "string" ? value.name : nestedName;
  if (value.type !== "function" || typeof name !== "string" || !toolNames.has(name)) return undefined;
  return { type: "function", name };
}

function normalizeToolArguments(argumentsJson: string): string {
  try {
    const parsed: unknown = JSON.parse(argumentsJson);
    return JSON.stringify(parsed);
  } catch {
    return argumentsJson;
  }
}

function normalizeXaiTurn(sessionId: string, userTurnCount: number): number {
  const now = Date.now();
  const existing = sessionTurns.get(sessionId);
  if (existing && now - existing.lastUsed > SESSION_TTL_MS) sessionTurns.delete(sessionId);
  const previous = sessionTurns.get(sessionId)?.turn ?? 0;
  const turn = Math.max(1, userTurnCount, previous + 1);
  while (sessionTurns.size >= MAX_TRACKED_SESSIONS) {
    const oldest = sessionTurns.keys().next().value;
    if (!oldest) break;
    sessionTurns.delete(oldest);
  }
  sessionTurns.set(sessionId, { turn, lastUsed: now });
  return turn;
}

/** Create Grok CLI correlation headers without persisting conversation content. */
export function xaiRequestContext(context: XaiRequestContext, req: CanonicalRequest, modelId: string): Required<XaiRequestContext> & { turn: number; modelId: string } {
  const sessionId = context.sessionId?.trim().slice(0, 256) || crypto.randomUUID();
  const requestId = context.requestId?.trim().slice(0, 256) || crypto.randomUUID();
  const userTurnCount = req.messages.filter((message) => message.role === "user").length;
  return { sessionId, requestId, turn: normalizeXaiTurn(sessionId, userTurnCount), modelId };
}

export function xaiChatCompletionsBody(req: CanonicalRequest, modelId: string): Record<string, unknown> {
  const messages: Array<Record<string, unknown>> = [];
  for (const message of req.messages) {
    const msg: Record<string, unknown> = { role: message.role };
    if (message.role === "tool") {
      msg.tool_call_id = message.tool_call_id;
      msg.content = textOf(message.content);
      messages.push(msg);
      continue;
    }
    if (Array.isArray(message.content)) {
      const parts: Array<Record<string, unknown>> = [];
      for (const part of message.content) {
        if (typeof part === "string") parts.push({ type: "text", text: part });
        else if (part.type === "text") parts.push({ type: "text", text: part.text });
        else if (part.type === "image_url") {
          parts.push({ type: "image_url", image_url: part.image_url });
        }
      }
      msg.content = parts;
    } else {
      msg.content = message.content ?? "";
    }
    if (message.tool_calls?.length) {
      msg.tool_calls = message.tool_calls.map((tc) => ({
        id: tc.id,
        type: "function",
        function: { name: tc.function.name, arguments: tc.function.arguments },
      }));
    }
    messages.push(msg);
  }

  const body: Record<string, unknown> = { model: modelId, messages };

  if (req.tools?.length) {
    body.tools = req.tools.map((tool) => {
      if (tool.type === "function" || (tool.function && typeof tool.function === "object")) {
        return { type: "function", function: tool.function };
      }
      return tool;
    });
    if (req.tool_choice !== undefined) body.tool_choice = req.tool_choice;
  }

  if (req.temperature !== undefined) body.temperature = req.temperature;
  if (req.top_p !== undefined) body.top_p = req.top_p;
  if (req.max_tokens !== undefined) body.max_tokens = req.max_tokens;

  // Reasoning: only set for models that support it (grok-4.5)
  if (req.reasoning?.enabled !== false && supportsReasoningEffort(modelId)) {
    body.reasoning_effort = normalizeEffort(req.reasoning?.effort as string | undefined);
  }

  return body;
}

export function xaiRequestBody(req: CanonicalRequest, modelId: string): Record<string, unknown> {
  const instructions: string[] = [];
  const input: Array<Record<string, unknown>> = [];
  const functionCallIds = new Set<string>();
  // `store: false` rejects server-generated call IDs. When a previous Grok
  // response is sent back with its tool result, rewrite both sides of that
  // pair consistently for this request.
  const normalizedFunctionCallIds = new Map<string, string>();

  for (const message of req.messages) {
    if (message.role === "system") {
      const text = textOf(message.content);
      if (text) instructions.push(text);
      continue;
    }
    if (message.role === "tool") {
      // A result without its call id cannot be associated safely by Grok.
      // Also skip results with server-generated call ids (store=false can't resolve them).
      const callId = message.tool_call_id && (normalizedFunctionCallIds.get(message.tool_call_id) ?? message.tool_call_id);
      if (callId && functionCallIds.has(callId)) {
        input.push({ type: "function_call_output", call_id: callId, output: textOf(message.content) });
      }
      continue;
    }

    const role = message.role === "assistant" ? "assistant" : "user";
    const contentType = role === "assistant" ? "output_text" : "input_text";
    const content: Array<Record<string, unknown>> = [];
    if (Array.isArray(message.content)) {
      for (const part of message.content) {
        if (typeof part === "string") content.push({ type: contentType, text: part });
        else if (part.type === "text") content.push({ type: contentType, text: part.text });
        else if (part.type === "image_url" && role === "user") {
          const image = part.image_url as { url?: unknown };
          if (typeof image.url === "string") content.push({ type: "input_image", image_url: image.url });
        }
      }
    } else if (message.content) {
      content.push({ type: contentType, text: message.content });
    }
    if (content.length) input.push({ type: "message", role, content });
    if (role === "assistant") {
      for (const call of message.tool_calls ?? []) {
        if (call.id && call.function.name) {
          // Strip server-generated call ids — store=false can't resolve them.
          const callId = isServerGeneratedId(call.id) ? crypto.randomUUID() : call.id;
          normalizedFunctionCallIds.set(call.id, callId);
          functionCallIds.add(callId);
          input.push({ type: "function_call", call_id: callId, name: call.function.name, arguments: normalizeToolArguments(call.function.arguments) });
        }
      }
    }
  }

  // Strip stored item references (server-generated ids that store=false can't resolve)
  // and filter orphaned function_call_output items.
  const finalInput = input.filter((item) => {
    if (typeof item === "string" && SERVER_ID_PATTERN.test(item)) return false;
    if (item.type === "item_reference") return false;
    if (item.type === "function_call_output") {
      return functionCallIds.has(item.call_id as string);
    }
    // Strip server-generated ids from items unless they're native Grok CLI ids
    if (typeof item.id === "string" && SERVER_ID_PATTERN.test(item.id) && !NATIVE_GROK_CLI_ITEM_ID.test(item.id)) {
      delete item.id;
    }
    return true;
  });

  const body: Record<string, unknown> = { model: modelId, input: finalInput, store: false, stream: true };
  if (req.tools?.length && supportsReasoningEffort(modelId)) instructions.push(VERIFIED_TOOL_WORKFLOW);
  if (instructions.length) body.instructions = instructions.join("\n\n");

  // Tools: flatten Chat Completions shape, keep hosted tools passthrough.
  if (req.tools?.length) {
    const flatTools: Array<Record<string, unknown>> = [];
    const toolNames = new Set<string>();
    for (const tool of req.tools) {
      const type = typeof tool.type === "string" ? tool.type : "";
      // Hosted tools (web_search, x_search, etc.) — passthrough as-is.
      if (HOSTED_TOOL_TYPES.has(type)) {
        flatTools.push({ type, ...("name" in tool && typeof tool.name === "string" ? { name: tool.name } : {}) });
        continue;
      }
      // Nested Chat Completions function shape → flat Responses format.
      const fn = tool.function;
      const name = fn?.name?.trim();
      if (!name) continue;
      flatTools.push({
        type: "function",
        name: name.slice(0, 128),
        ...(fn?.description ? { description: fn.description } : {}),
        parameters: fn?.parameters && typeof fn.parameters === "object" && !Array.isArray(fn.parameters)
          ? fn.parameters
          : { type: "object", properties: {} },
      });
      toolNames.add(name);
    }
    if (flatTools.length) {
      body.tools = flatTools;
      const choice = xaiToolChoice(req.tool_choice, toolNames);
      if (choice !== undefined) body.tool_choice = choice;
    }
  }

  if (req.temperature !== undefined) body.temperature = req.temperature;
  if (req.top_p !== undefined) body.top_p = req.top_p;
  if (req.max_tokens !== undefined) body.max_output_tokens = req.max_tokens;

  // Reasoning: only set effort for models that support it (grok-4.5).
  // grok-build rejects reasoningEffort but still accepts summary + encrypted_content.
  if (req.reasoning?.enabled !== false) {
    const reasoning: Record<string, unknown> = { summary: "concise" };
    // Grok-4.5 supports low/medium/high. Always use its maximum effective
    // effort so coding and tool requests receive enough planning budget.
    if (supportsReasoningEffort(modelId)) reasoning.effort = "high";
    body.reasoning = reasoning;
    // Encrypted reasoning for multi-turn continuity (official CLI always requests this).
    const include: string[] = ["reasoning.encrypted_content"];
    body.include = include;
  }

  // Drop fields not recognized by Responses API
  for (const k of Object.keys(body)) {
    if (!RESPONSES_API_ALLOWLIST.has(k)) delete body[k];
  }

  return body;
}

export function xaiHeaders(
  accessToken: string,
  stream = false,
  context?: Required<XaiRequestContext> & { turn?: number; modelId?: string },
  account?: ProviderAccount,
): Record<string, string> {
  const email = account ? (extractEmailFromAccessToken(accessToken) ?? account.label) : undefined;
  // Generate a stable agent id from the account id (official CLI sends this header)
  const agentId = account ? `mi-${account.id.slice(0, 8)}-${account.id.slice(8, 12)}-${account.id.slice(12, 16)}` : undefined;
  return {
    "content-type": "application/json",
    Authorization: `Bearer ${accessToken}`,
    "User-Agent": "xai-grok-cli",
    "x-grok-client-version": "0.2.103",
    "x-grok-client-identifier": "grok-shell",
    ...(email ? { "x-email": email } : {}),
    ...(context ? {
      "x-grok-session-id": context.sessionId,
      "x-grok-conv-id": context.sessionId,
      "x-grok-req-id": context.requestId,
      "x-grok-turn-idx": String(context.turn ?? 1),
      ...(context.modelId ? { "x-grok-model-override": context.modelId } : {}),
    } : {}),
    ...(agentId ? { "x-grok-agent-id": agentId } : {}),
    ...(stream ? { accept: "text/event-stream" } : {}),
  };
}

/** Retry transient Grok CLI failures only before an SSE body is consumed. */
export async function fetchXaiResponses(
  init: RequestInit,
  signal?: AbortSignal,
): Promise<Response> {
  const abortSignal = signal ?? init.signal ?? undefined;
  let response = await fetch(xaiResponsesUrl(), init);
  if (!RETRIABLE_XAI_STATUSES.has(response.status) || abortSignal?.aborted) return response;
  const retryAfter = Number(response.headers.get("retry-after"));
  const waitMs = Number.isFinite(retryAfter) && retryAfter > 0 ? Math.min(retryAfter * 1_000, 2_000) : 250;
  await new Promise<void>((resolve, reject) => {
    const timer = setTimeout(resolve, waitMs);
    abortSignal?.addEventListener("abort", () => {
      clearTimeout(timer);
      reject(abortSignal.reason);
    }, { once: true });
  });
  await response.body?.cancel();
  return fetch(xaiResponsesUrl(), init);
}

/** Retry transient Grok CLI failures for Chat Completions endpoint. */
export async function fetchXaiChatCompletions(
  init: RequestInit,
  signal?: AbortSignal,
): Promise<Response> {
  const abortSignal = signal ?? init.signal ?? undefined;
  let response = await fetch(xaiChatCompletionsUrl(), init);
  if (!RETRIABLE_XAI_STATUSES.has(response.status) || abortSignal?.aborted) return response;
  const retryAfter = Number(response.headers.get("retry-after"));
  const waitMs = Number.isFinite(retryAfter) && retryAfter > 0 ? Math.min(retryAfter * 1_000, 2_000) : 250;
  await new Promise<void>((resolve, reject) => {
    const timer = setTimeout(resolve, waitMs);
    abortSignal?.addEventListener("abort", () => {
      clearTimeout(timer);
      reject(abortSignal.reason);
    }, { once: true });
  });
  await response.body?.cancel();
  return fetch(xaiChatCompletionsUrl(), init);
}

export async function ensureFreshXaiToken(repo: ProvidersRepo, account: ProviderAccount): Promise<string> {
  if (!account.expires_at || account.expires_at - Date.now() > REFRESH_THRESHOLD_MS) return account.api_key;
  if (!account.refresh_token) {
    throw markReauthRequired(repo, account, "Grok login has expired and cannot be refreshed.");
  }

  return withRefreshLock(account.id, async () => {
    try {
      const tokens = await refreshAccessToken(account.refresh_token!);
      const expiresAt = tokens.expires_in ? Date.now() + tokens.expires_in * 1000 : null;
      repo.updateAccountOAuth(account.id, { refreshToken: tokens.refresh_token ?? account.refresh_token, expiresAt });
      repo.updateAccount(account.id, { apiKey: tokens.access_token });
      account.api_key = tokens.access_token;
      account.refresh_token = tokens.refresh_token ?? account.refresh_token;
      account.expires_at = expiresAt;
      return tokens.access_token;
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      const status = err instanceof AdminError ? err.status : 0;
      if (isPermanentRefreshFailure(status, detail)) {
        throw markReauthRequired(repo, account, `Grok token refresh failed: ${detail}.`);
      }
      throw new GatewayError(502, "server_error", `Grok token refresh failed: ${detail}`);
    }
  });
}

// ── xAI Grok Responses API → Chat Completions translator ──
//
// Grok CLI uses the Responses API SSE dialect (same shape as Codex) but
// Grok-4.5 is a reasoning model that emits response.reasoning_text.delta
// events before visible output. This translator handles those events
// explicitly so clients see progress during the reasoning phase.

export class XaiStreamTranslator {
  private id = `chatcmpl-${ulid()}`;
  private created = Math.floor(Date.now() / 1000);
  private model: string;
  private started = false;
  private usage: Usage | null = null;
  private sawToolCall = false;
  private nextToolCallIndex = 0;
  private toolCallIndices = new Map<string, number>();
  private toolCallArguments = new Map<number, string>();
  private outputToolCallIndices = new Map<number, number>();
  // Grok 4.6 (and some builds) emit tool calls as plain text of the form
  // "tool_calls:\n- <name>\n<json args>" inside output_text.delta instead of
  // structured function_call items. Buffer content and convert that pattern
  // into delta.tool_calls so clients never see the raw marker.
  private textBuffer = "";
  private grokToolBuffer: string | null = null;

  constructor(model: string) {
    this.model = model;
  }

  handleEvent(event: string, data: string): string[] {
    const out: string[] = [];
    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(data) as Record<string, unknown>;
    } catch {
      return out;
    }
    const type = (parsed.type as string | undefined) ?? event;

    const startChunk = (): string => {
      this.started = true;
      return this.chunk({ role: "assistant", content: "" }, null);
    };

    switch (type) {
      case "response.created": {
        const r = parsed.response as Record<string, unknown> | undefined;
        if (r?.id) this.id = `chatcmpl-${r.id as string}`;
        if (!this.started) out.push(startChunk());
        break;
      }
      case "response.output_item.added": {
        const item = parsed.item as Record<string, unknown> | undefined;
        if (item?.type === "function_call") {
          this.sawToolCall = true;
          if (!this.started) out.push(startChunk());
          const index = this.nextToolCallIndex++;
          const callId = (item.call_id ?? item.id ?? `call_${ulid()}`) as string;
          if (typeof item.id === "string") this.toolCallIndices.set(item.id, index);
          if (typeof item.call_id === "string") this.toolCallIndices.set(item.call_id, index);
          if (typeof parsed.output_index === "number") this.outputToolCallIndices.set(parsed.output_index, index);
          this.toolCallArguments.set(index, "");
          out.push(
            this.chunk(
              {
                tool_calls: [
                  {
                    index,
                    id: callId,
                    type: "function",
                    function: { name: (item.name ?? "") as string, arguments: "" },
                  },
                ],
              },
              null,
            ),
          );
        } else if (item?.type === "message") {
          // New message output item — ensure stream is alive.
          if (!this.started) out.push(startChunk());
        }
        break;
      }
      case "response.content_part.added": {
        // New content part — keep the stream alive.
        if (!this.started) out.push(startChunk());
        break;
      }
      case "response.output_text.delta":
      case "response.refusal.delta": {
        const delta = parsed.delta as string | undefined;
        if (delta) {
          if (!this.started) out.push(startChunk());
          this.processTextDelta(delta, out);
        }
        break;
      }
      // ── Grok-4.5 reasoning events ──
      case "response.reasoning_text.delta": {
        const delta = parsed.delta as string | undefined;
        if (delta) {
          if (!this.started) out.push(startChunk());
          out.push(this.chunk({ reasoning_content: delta }, null));
        }
        break;
      }
      case "response.reasoning_summary_text.delta": {
        const delta = parsed.delta as string | undefined;
        if (delta) {
          if (!this.started) out.push(startChunk());
          // xAI explicitly labels this as a summary. Keep it in the dedicated
          // reasoning channel so it is visible to reasoning-aware clients but
          // never contaminates the answer or tool-call protocol.
          out.push(this.chunk({ reasoning_content: delta }, null));
        }
        break;
      }
      case "response.reasoning_text.done":
      case "response.reasoning_summary_text.done":
      case "response.output_text.done":
      case "response.content_part.done":
      case "response.output_item.done": {
        const item = parsed.item as Record<string, unknown> | undefined;
        if (item?.type === "function_call") {
          const itemId = typeof item.id === "string" ? item.id : "";
          const callId = typeof item.call_id === "string" ? item.call_id : "";
          const outputIndex = typeof parsed.output_index === "number" ? parsed.output_index : 0;
          const index = this.toolCallIndices.get(itemId) ?? this.toolCallIndices.get(callId) ?? this.outputToolCallIndices.get(outputIndex) ?? outputIndex;
          const argumentsValue = typeof item.arguments === "string" ? item.arguments : "";
          const emitted = this.toolCallArguments.get(index) ?? "";
          if (argumentsValue.startsWith(emitted) && argumentsValue.length > emitted.length) {
            const remaining = argumentsValue.slice(emitted.length);
            this.toolCallArguments.set(index, argumentsValue);
            out.push(this.chunk({ tool_calls: [{ index, function: { arguments: remaining } }] }, null));
          }
        }
        // Terminal events for sub-parts — keep stream alive.
        if (!this.started) out.push(startChunk());
        break;
      }
      // ── end reasoning events ──
      case "response.function_call_arguments.delta": {
        const delta = parsed.delta as string | undefined;
        if (delta) {
          if (!this.started) out.push(startChunk());
          const itemId = typeof parsed.item_id === "string" ? parsed.item_id : "";
          const callId = typeof parsed.call_id === "string" ? parsed.call_id : "";
          const outputIndex = typeof parsed.output_index === "number" ? parsed.output_index : 0;
          const index = this.toolCallIndices.get(itemId) ?? this.toolCallIndices.get(callId) ?? this.outputToolCallIndices.get(outputIndex) ?? outputIndex;
          this.toolCallArguments.set(index, (this.toolCallArguments.get(index) ?? "") + delta);
          out.push(this.chunk({ tool_calls: [{ index, function: { arguments: delta } }] }, null));
        }
        break;
      }
      case "response.completed":
      case "response.incomplete": {
        const r = parsed.response as ResponsesApiResponse | undefined;
        if (r?.usage) this.usage = normalizeUsage(r.usage);
        if (!this.started) out.push(startChunk());
        this.flushPendingText(out);
        out.push(this.chunk({}, this.sawToolCall ? "tool_calls" : "stop"));
        out.push("data: [DONE]\n\n");
        break;
      }
      case "response.failed": {
        const r = parsed.response as ResponsesApiResponse | undefined;
        if (r?.usage) this.usage = normalizeUsage(r.usage);
        const error = r?.error as Record<string, unknown> | undefined;
        const message = typeof error?.message === "string" ? error.message : "Grok response failed";
        out.push(`data: ${JSON.stringify({ error: { message, type: "server_error" } })}\n\n`);
        out.push("data: [DONE]\n\n");
        break;
      }
      case "error": {
        const msg = (parsed.error as Record<string, unknown> | undefined)?.message ?? parsed.message ?? "upstream stream error";
        out.push(`data: ${JSON.stringify({ error: { message: msg, type: "server_error" } })}\n\n`);
        out.push("data: [DONE]\n\n");
        break;
      }
      default:
        break;
    }
    return out;
  }

  result(): { usage: Usage | null } {
    return { usage: this.usage };
  }

  /** Flush any buffered text/tool-call content at the end of the stream. */
  finish(): string[] {
    const out: string[] = [];
    this.flushPendingText(out);
    return out;
  }

  /**
   * Grok 4.6 emits tool calls as plain text of the form:
   *
   *   tool_calls:
   *   - run_command
   *   {"command":"...","timeout_ms":20000.0}
   *
   * This method buffers content deltas and, when that pattern is detected,
   * emits delta.tool_calls instead of forwarding the raw marker text.
   */
  private processTextDelta(text: string, out: string[]): void {
    if (this.grokToolBuffer !== null) {
      this.grokToolBuffer += text;
      this.flushGrokToolBuffer(out);
      return;
    }
    this.textBuffer += text;
    const markerIndex = this.textBuffer.search(/tool_calls\s*:/i);
    if (markerIndex === -1) {
      const keep = Math.min(this.textBuffer.length, 64);
      const emitText = this.textBuffer.slice(0, -keep);
      if (emitText) out.push(this.chunk({ content: emitText }, null));
      this.textBuffer = this.textBuffer.slice(-keep);
      return;
    }
    const before = this.textBuffer.slice(0, markerIndex);
    if (before) out.push(this.chunk({ content: before }, null));
    this.grokToolBuffer = this.textBuffer.slice(markerIndex);
    this.textBuffer = "";
    this.flushGrokToolBuffer(out);
  }

  private flushGrokToolBuffer(out: string[]): void {
    const buffer = this.grokToolBuffer;
    if (buffer === null) return;
    const nameMatch = buffer.match(/tool_calls\s*:\s*[\r\n]+\s*-\s*([A-Za-z_][\w.-]*)[\r\n]+/);
    if (!nameMatch) {
      if (buffer.length > 512) {
        out.push(this.chunk({ content: buffer }, null));
        this.grokToolBuffer = null;
      }
      return;
    }
    const jsonStart = nameMatch.index! + nameMatch[0].length;
    if (buffer[jsonStart] !== "{") {
      if (buffer.length > 512) {
        out.push(this.chunk({ content: buffer }, null));
        this.grokToolBuffer = null;
      }
      return;
    }
    const end = this.findJsonEnd(buffer, jsonStart);
    if (end === -1) return; // wait for the rest of the JSON

    const name = nameMatch[1];
    const args = buffer.slice(jsonStart, end);
    const index = this.nextToolCallIndex++;
    const callId = `call_${ulid()}`;
    this.toolCallIndices.set(callId, index);
    this.toolCallArguments.set(index, args);
    this.sawToolCall = true;
    out.push(this.chunk({
      tool_calls: [{ index, id: callId, type: "function", function: { name, arguments: "" } }],
    }, null));
    out.push(this.chunk({ tool_calls: [{ index, function: { arguments: args } }] }, null));

    const tail = buffer.slice(end);
    this.grokToolBuffer = tail.length > 512 ? null : tail;
    if (tail) out.push(this.chunk({ content: tail }, null));
  }

  /** Return the index just past the balanced JSON object starting at `start`, or -1. */
  private findJsonEnd(buffer: string, start: number): number {
    let depth = 0;
    let inString = false;
    let escaped = false;
    for (let i = start; i < buffer.length; i++) {
      const ch = buffer[i];
      if (inString) {
        if (escaped) escaped = false;
        else if (ch === "\\") escaped = true;
        else if (ch === '"') inString = false;
        continue;
      }
      if (ch === '"') { inString = true; continue; }
      if (ch === "{") depth += 1;
      else if (ch === "}") {
        depth -= 1;
        if (depth === 0) return i + 1;
      }
    }
    return -1;
  }

  private flushPendingText(out: string[]): void {
    if (this.grokToolBuffer !== null) {
      // A dangling tool_calls marker with no completed block — emit as text.
      if (this.grokToolBuffer) out.push(this.chunk({ content: this.grokToolBuffer }, null));
      this.grokToolBuffer = null;
    }
    if (this.textBuffer) {
      out.push(this.chunk({ content: this.textBuffer }, null));
      this.textBuffer = "";
    }
  }

  private chunk(delta: Record<string, unknown>, finishReason: string | null): string {
    const obj = {
      id: this.id,
      object: "chat.completion.chunk",
      created: this.created,
      model: this.model,
      choices: [{ index: 0, delta, finish_reason: finishReason }],
    };
    return `data: ${JSON.stringify(obj)}\n\n`;
  }
}

interface ResponsesApiResponse {
  id?: string;
  model?: string;
  status?: string;
  output?: Array<Record<string, unknown>>;
  usage?: { input_tokens?: number; output_tokens?: number; total_tokens?: number };
  error?: { message?: string };
}

/**
 * Aggregate Grok CLI Responses API SSE stream into a single chat.completion.
 * Handles reasoning_text.delta events from Grok-4.5 so non-streaming clients
 * receive the full output (reasoning + visible text).
 */
export async function aggregateXaiResponsesStream(
  body: ReadableStream<Uint8Array>,
  requestedModel: string,
): Promise<CanonicalResponse> {
  const parser = new SseParser();
  const translator = new XaiStreamTranslator(requestedModel);
  const decoder = new TextDecoder();
  const reader = body.getReader();
  let text = "";
  const toolCalls = new Map<number, { id: string; name: string; arguments: string }>();
  let finishReason: string | null = null;

  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      const chunk = decoder.decode(value, { stream: true });
      for (const ev of parser.feed(chunk)) {
        if (ev.data === "[DONE]") continue;
        let parsed: Record<string, unknown>;
        try {
          parsed = JSON.parse(ev.data) as Record<string, unknown>;
        } catch {
          continue;
        }
        const type = (parsed.type as string | undefined) ?? ev.event;
        if (type === "response.output_text.delta" || type === "response.refusal.delta") {
          text += (parsed.delta as string | undefined) ?? "";
        } else if (type === "response.reasoning_text.delta" || type === "response.reasoning_summary_text.delta") {
          text += (parsed.delta as string | undefined) ?? "";
        } else if (type === "response.output_item.added") {
          const item = parsed.item as Record<string, unknown> | undefined;
          if (item?.type === "function_call") {
            toolCalls.set(toolCalls.size, {
              id: (item.call_id ?? item.id ?? `call_${ulid()}`) as string,
              name: (item.name ?? "") as string,
              arguments: "",
            });
          }
        } else if (type === "response.function_call_arguments.delta") {
          const idx = (parsed.output_index as number | undefined) ?? toolCalls.size - 1;
          const tc = toolCalls.get(Math.max(0, idx)) ?? toolCalls.get(toolCalls.size - 1);
          if (tc) tc.arguments += (parsed.delta as string | undefined) ?? "";
        } else if (type === "response.completed" || type === "response.incomplete" || type === "response.failed") {
          finishReason = toolCalls.size ? "tool_calls" : "stop";
        }
        // Feed translator for usage capture.
        translator.handleEvent(ev.event, ev.data);
      }
    }
  } finally {
    reader.releaseLock();
  }

  const usage = translator.result().usage;
  const message: CanonicalResponse["choices"][number]["message"] = { role: "assistant", content: text };
  if (toolCalls.size) {
    message.tool_calls = [...toolCalls.values()].map((tc) => ({
      id: tc.id,
      type: "function" as const,
      function: { name: tc.name, arguments: tc.arguments },
    }));
  }
  return {
    id: `chatcmpl-${ulid()}`,
    object: "chat.completion",
    created: Math.floor(Date.now() / 1000),
    model: requestedModel,
    choices: [{ index: 0, message, finish_reason: finishReason ?? "stop" }],
    ...(usage ? { usage } : {}),
  };
}

/**
 * Aggregate a Grok CLI Chat Completions SSE stream into a single
 * CanonicalResponse. Chat Completions returns standard OpenAI SSE chunks so
 * this is a straightforward aggregation — no translator needed.
 */
export async function aggregateXaiChatCompletionsStream(
  body: ReadableStream<Uint8Array>,
  requestedModel: string,
): Promise<CanonicalResponse> {
  const parser = new SseParser();
  const decoder = new TextDecoder();
  const reader = body.getReader();
  let text = "";
  let reasoningText = "";
  const toolCalls = new Map<number, { id: string; name: string; arguments: string }>();
  let finishReason: string | null = null;
  let usage: Usage | null = null;

  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      const chunk = decoder.decode(value, { stream: true });
      for (const ev of parser.feed(chunk)) {
        if (ev.data === "[DONE]") continue;
        let parsed: Record<string, unknown>;
        try {
          parsed = JSON.parse(ev.data) as Record<string, unknown>;
        } catch {
          continue;
        }
        const choices = parsed.choices as Array<Record<string, unknown>> | undefined;
        const choice = choices?.[0];
        if (!choice) continue;
        const delta = choice.delta as Record<string, unknown> | undefined;
        if (delta?.content) text += delta.content as string;
        if (delta?.reasoning_content) reasoningText += delta.reasoning_content as string;
        if (delta?.tool_calls) {
          const tcs = delta.tool_calls as Array<Record<string, unknown>>;
          for (const tc of tcs) {
            const idx = (tc.index as number) ?? toolCalls.size;
            const existing = toolCalls.get(idx);
            if (tc.id) {
              const tcFunc = tc.function as Record<string, unknown> | undefined;
              toolCalls.set(idx, {
                id: tc.id as string,
                name: tcFunc?.name as string ?? existing?.name ?? "",
                arguments: tcFunc?.arguments as string ?? existing?.arguments ?? "",
              });
            } else if (existing) {
              const tcFunc = tc.function as Record<string, unknown> | undefined;
              if (tcFunc?.name) existing.name = tcFunc.name as string;
              if (tcFunc?.arguments) existing.arguments += tcFunc.arguments as string;
            }
          }
        }
        if (choice.finish_reason) finishReason = choice.finish_reason as string;
        if (parsed.usage) usage = parsed.usage as Usage;
      }
    }
  } finally {
    reader.releaseLock();
  }

  // Prepend reasoning text to content if present (Mirais convention)
  const fullContent = reasoningText ? `${reasoningText}\n${text}` : text;

  const message: CanonicalResponse["choices"][number]["message"] = { role: "assistant", content: fullContent };
  if (toolCalls.size) {
    message.tool_calls = [...toolCalls.values()].map((tc) => ({
      id: tc.id,
      type: "function" as const,
      function: { name: tc.name, arguments: tc.arguments },
    }));
  }
  return {
    id: `chatcmpl-${ulid()}`,
    object: "chat.completion",
    created: Math.floor(Date.now() / 1000),
    model: requestedModel,
    choices: [{ index: 0, message, finish_reason: finishReason ?? "stop" }],
    ...(usage ? { usage } : {}),
  };
}

/**
 * Wrap a Grok CLI Chat Completions SSE stream as an OpenAI-compatible
 * chat.completion.chunk stream. Since upstream already returns standard
 * OpenAI SSE chunks, this is a near-pass-through — we just re-emit the
 * parsed chunks with a Mirais-generated id and model.
 */
export function xaiChatCompletionsStreamToChat(
  body: ReadableStream<Uint8Array>,
  requestedModel: string,
): { stream: ReadableStream<Uint8Array>; usagePromise: Promise<Usage | null> } {
  const parser = new SseParser();
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();
  let resolveUsage: (u: Usage | null) => void;
  const usagePromise = new Promise<Usage | null>((r) => { resolveUsage = r; });
  const chatId = `chatcmpl-${ulid()}`;
  let usage: Usage | null = null;

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const reader = body.getReader();
      try {
        for (;;) {
          const { done, value } = await reader.read();
          if (done) break;
          const chunk = decoder.decode(value, { stream: true });
          for (const ev of parser.feed(chunk)) {
            if (ev.data === "[DONE]") {
              controller.enqueue(encoder.encode("data: [DONE]\n\n"));
              continue;
            }
            let parsed: Record<string, unknown>;
            try {
              parsed = JSON.parse(ev.data) as Record<string, unknown>;
            } catch {
              continue;
            }
            // Override id and model with Mirais values
            parsed.id = chatId;
            parsed.model = requestedModel;
            if (parsed.usage) usage = parsed.usage as Usage;
            controller.enqueue(encoder.encode(`data: ${JSON.stringify(parsed)}\n\n`));
          }
        }
        for (const ev of parser.finish()) {
          if (ev.data === "[DONE]") {
            controller.enqueue(encoder.encode("data: [DONE]\n\n"));
            continue;
          }
          let parsed: Record<string, unknown>;
          try {
            parsed = JSON.parse(ev.data) as Record<string, unknown>;
          } catch {
            continue;
          }
          parsed.id = chatId;
          parsed.model = requestedModel;
          if (parsed.usage) usage = parsed.usage as Usage;
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(parsed)}\n\n`));
        }
      } finally {
        reader.releaseLock();
        resolveUsage(usage);
        controller.close();
      }
    },
  });

  return { stream, usagePromise };
}

/**
 * Wrap a Grok CLI Responses API SSE stream as an OpenAI chat.completion.chunk
 * stream. Handles Grok-4.5 reasoning events natively.
 */
export function xaiResponsesStreamToChat(
  body: ReadableStream<Uint8Array>,
  requestedModel: string,
): { stream: ReadableStream<Uint8Array>; usagePromise: Promise<Usage | null> } {
  const parser = new SseParser();
  const translator = new XaiStreamTranslator(requestedModel);
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();
  let resolveUsage: (u: Usage | null) => void;
  const usagePromise = new Promise<Usage | null>((r) => { resolveUsage = r; });

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const reader = body.getReader();
      try {
        for (;;) {
          const { done, value } = await reader.read();
          if (done) break;
          const text = decoder.decode(value, { stream: true });
          for (const ev of parser.feed(text)) {
            if (ev.data === "[DONE]") continue;
            for (const line of translator.handleEvent(ev.event, ev.data)) {
              controller.enqueue(encoder.encode(line));
            }
          }
        }
        for (const ev of parser.finish()) {
          if (ev.data === "[DONE]") continue;
          for (const line of translator.handleEvent(ev.event, ev.data)) {
            controller.enqueue(encoder.encode(line));
          }
        }
        for (const line of translator.finish()) {
          controller.enqueue(encoder.encode(line));
        }
      } catch (err) {
        const detail = err instanceof Error ? err.name : "UnknownError";
        controller.enqueue(encoder.encode(`data: ${JSON.stringify({ error: { message: `upstream stream error (${detail})`, type: "server_error" } })}\n\n`));
        controller.enqueue(encoder.encode("data: [DONE]\n\n"));
      } finally {
        reader.releaseLock();
        resolveUsage(translator.result().usage);
        controller.close();
      }
    },
  });

  return { stream, usagePromise };
}