CREATE TABLE IF NOT EXISTS request_log_payload_cleanup (
  id TINYINT UNSIGNED NOT NULL,
  cursor_id VARCHAR(64) NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO request_log_payload_cleanup (id) VALUES (1) ON DUPLICATE KEY UPDATE id = id;
